var symmetricCrypto = require("@hugoalh/symmetric-crypto");
var data = "Hello, world!\nFoo.\nBar.";
var passphrase = "githubnode";
var firstEncrypted = symmetricCrypto.encrypt(data, passphrase);
var secondEncrypted = symmetricCrypto.encryptMultipleLine(data, passphrase);
console.log(firstEncrypted);
console.log(secondEncrypted);
var firstDecrypted = symmetricCrypto.decrypt(firstEncrypted, passphrase);
var secondDecrypted = symmetricCrypto.decryptMultipleLine(secondEncrypted, passphrase);
console.log(firstDecrypted);
console.log(secondDecrypted);
