# $<Schema>$ https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
name: "Bug Report (Form Edition)"
description: "Report a bug."
labels:
  - "ðŸ›bug"
  - "ðŸ”µunconfirm"
body:
  - type: "markdown"
    attributes:
      value: "> **ðŸ§ª Experimental:** GitHub Issue Form is currently in beta; If encounter any issue(s), please use the Markdown edition."
  - type: "textarea"
    id: "describe"
    attributes:
      label: "Describe"
      description: "What the bug is?"
    validations:
      required: false
  - type: "dropdown"
    id: "version"
    attributes:
      label: "Version"
      description: "What version(s) is affected? Must be a supported version(s) listed in the \"Security Policy\" (/.github/SECURITY.md)."
      multiple: true
      options:
        - "v1.2.7"
        - "v1.2.6"
        - "v1.2.5"
        - "v1.2.4"
        - "v1.2.3"
        - "v1.2.2"
        - "v1.2.1"
        - "v1.2.0"
    validations:
      required: false
  - type: "textarea"
    id: "reproduce"
    attributes:
      label: "To Reproduce"
      description: "If this bug can be reproduce, please list the step(s)!"
    validations:
      required: false
  - type: "textarea"
    id: "expected-behavior"
    attributes:
      label: "Expected Behavior"
      description: "What thing(s) should expected to happen?"
    validations:
      required: false
  - type: "textarea"
    id: "additional"
    attributes:
      label: "Additional"
      description: "If there has any information that related to this issue but not suitable to the other field(s), please list it here."
    validations:
      required: false
